# docker-compose.yaml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=efimka48
      - DB_NAME=library
      - DB_PORT=5432
      - GIN_MODE=release
    networks:
      - library-network

  db:
    image: postgres:15-alpine
    container_name: library-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=efimka48
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data:
